# Generated by Django 5.1.3 on 2024-11-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiorecord',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='media/audio_files/'),
        ),
    ]
